apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: uptime-kuma
  namespace: flux-system
spec:
  interval: 30s
  url: https://dirsigler.github.io/uptime-kuma-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: dependencies
spec:
  chart:
    spec:
      chart: uptime-kuma
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: flux-system
      version: 2.21.2
      interval: 1m0s
  interval: 30s
  values:
    nameOverride: "uptime-kuma"
    fullnameOverride: "uptime-kuma"
    namespaceOverride: "dependencies"
    service:
      type: ClusterIP
      port: 80
      nodePort:
      annotations: {}
    ingress:
      enabled: true
      className: "traefik"
      annotations: {}
      hosts:
        - host: uptime-kuma.application.local
          paths:
            - path: /
              pathType: Prefix
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    volume:
      enabled: false