---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: example-app-helm
  namespace: application
spec:
  interval: 30s
  releaseName: example-app-helm
  chart:
    spec:
      chart: ./charts/dfg-chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 30s
  values:
    replicaCount: 3
    image:
      repository: "eltrovert/example-app" # {"$imagepolicy": "flux-system:example-app:name"}
      tag: "1.0.2" # {"$imagepolicy": "flux-system:example-app:tag"}
    imagePullSecrets: dockerhub-key
    ingress:
      enabled: true
      className: "traefik"
      annotations: {}
      hosts:
        - host: gitops-helm.application.local
          paths:
            - path: /
              pathType:  Prefix
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi